# These are supported funding model platforms

github: [alisio85]

# Custom funding platforms
custom:
  - name: Patreon
    url: https://www.patreon.com/shadowbound
  - name: Ko-fi
    url: https://ko-fi.com/shadowbound
  - name: PayPal
    url: https://www.paypal.com/paypalme/shadowbound
